# Generated by Django 5.2.6 on 2025-09-11 16:16

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.file_dir_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
