# Generated by Django 5.2.6 on 2025-09-12 17:12

import Accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_avatar_alter_account_display_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', Accounts.models.AccountManager()),
            ],
        ),
    ]
