# Generated by Django 5.2.6 on 2025-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
