# Generated by Django 5.2.6 on 2025-09-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_account_is_staff_account_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='access_token',
        ),
    ]
