# Generated by Django 5.2.6 on 2025-09-20 15:17

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_unknown_contacts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='show_last_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.file_dir_path, validators=[Accounts.models.image_validate]),
        ),
    ]
